### PR TITLE
Add TypeScript and generate declaration files

### PR DESCRIPTION
**Pull request by thibaultboursier**
## Description
By adding [TypeScript](https://www.typescriptlang.org/), we secure the code and allow the generation of declaration files dynamically. 

👉 **Rather than having a declaration file manually written, it will be generated each time project is built.**

### What I did:
- Add [TypeScript](https://www.typescriptlang.org/) dependency, with configuration file.
- Update packages related to [Rollup](https://rollupjs.org/guide/en/)/[Rollup plugins](https://github.com/rollup/plugins).
- Update packages related to [Babel](https://babeljs.io/).
- Migrate `.js` modules to `.ts`/`.tsx`.
- Add some declaration types as dependencies.

Capture d’écran 2020-07-30 à 00 44 31

### CODE REVIEW

**Comment by alexfrancavilla** [comment]
@thibaultboursier @danalloway Any information on why this PR was closed? The diff looks pretty good and having Typescript declarations are important for many projects (as seen in #16).

**Comment by thibaultboursier** [comment]
Hello @alexfrancavilla, I closed it because @danalloway prefered static types file:
https://github.com/danalloway/react-country-flag/issues/16#issuecomment-668294817
Anyway, it works fine with this PR. Maybe @danalloway could consider it again ;-) ?

**Comment by forgowhisky** [comment]
Great but cant install @types/react-country-flag

**Comment by forgowhisky** [comment]
> Hello @alexfrancavilla, I closed it because @danalloway prefered static types file: [#16 (comment)](https://github.com/danalloway/react-country-flag/issues/16#issuecomment-668294817) Anyway, it works fine with this PR. Maybe @danalloway could consider it again ;-) ?

a year later, still waiting on a types file so I can use this in my ts project!

**Comment by thibaultboursier** [comment]
@forgowhisky I could create a fork of this project and publish it with types.

**Pull request closed without merging**
