### PR TITLE
adding options for sizing

### PR DESCRIPTION
**Pull request by patrickus**

### CODE REVIEW

**Comment by Zhongweizhao** [comment]
Why is this closed? It could be a really handy feature

**Comment by patrickus** [comment]
Reopened

**Comment by danalloway** [comment]
excellent suggestion!

pushing a change where you can now override any of the style props by passing in `styleProp`, and I added support for the `cdnUrl` as well

thank you!

**Comment by danalloway** [comment]
v0.2.0 live on NPM

**Pull request closed without merging**
