### PR TITLE
Readme CDN Url Version Upgraded, Github Url Added.

### PR DESCRIPTION
**Pull request by ramazansancar**

### CODE REVIEW

**Review by danalloway — APPROVED** [review]
thank you!

**Comment by NotTsunami** [comment]
@danalloway If you didn't know, upstream renamed from `flag-icon-css` to `flag-icons` and the latest version is 6.6.6. Missing a few new flags and lots of bug fixes/corrections to flags!

**Comment by ramazansancar** [comment]
> @danalloway If you didn't know, upstream renamed from `flag-icon-css` to `flag-icons` and the latest version is 6.6.6. Missing a few new flags and lots of bug fixes/corrections to flags! I can send in a PR if you wish, updating the CDN link.

Yes that's right you can check it here: https://www.npmjs.com/package/flag-icon-css

**Comment by ramazansancar** [comment]
Current Url: `https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css`

**Comment by danalloway** [comment]
fixed in version 3.1.0 along with other updates

**Pull request closed without merging**
